services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: golang_mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: golang_mysql
    command: ["migrate", "up"]

  seed:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: golang_mysql
    command: ["seed", "1000000"]

  app:
    build: .
    depends_on:
      seed:
        condition: service_completed_successfully
    environment:
      APP_PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: golang_mysql
    ports:
      - "8080:8080"
    command: ["serve"]
